### ISSUE TITLE
Build Failure : Am I missing something ?

### ISSUE THREAD

**Issue by bismoy2013** [airbnb/airpal#117]
Command used : gradle clean build .

                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/Users/bismoymurasing/Desktop/OpenSource/airpal/src/main/resources/assets/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy/index.js:108:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bismoymurasing/Desktop/OpenSource/airpal/src/main/resources/assets/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
:buildAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildAssets'.
> Process 'command '/Users/bismoymurasing/.gradle/nodejs/node-v0.10.33-darwin-x64/bin/node'' finished with non-zero exit value 8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 2.425 secs
BISMOYs-MacBook-Air:airpal bismoymurasing$

**Comment by suryaveer** [comment]
This worked for me on mac:
edit ```src/main/resources/assets/package.json``` and change ```browser-sync``` to ```~2.6.5```

hope that helps!

**Comment by haitaoyao** [comment]
who can give me a binary download link? After change the ```browser-sync ``` version to ``` 2.6.5 ``` it still fails to compile app.js and plugin.js so I got 404 on the landing page.

**Comment by tonywutao** [comment]
edit src/main/resources/assets/package.json and change browser-sync to ~2.8.1, works for my on ubuntu14.04

**Comment by rraghuram64** [comment]
Hey Guys,

I am using the gradle-2.8 and when I execute the following command ./gradlew clean shadowJar


FAILURE: Build failed with an exception.

* What went wrong:
Task 'build' not found in root project 'gradle-2.8'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Any help would be appreciated.
