### ISSUE TITLE
Cannot find module 'cl-strings'

### ISSUE THREAD

**Issue by ricdong** [airbnb/airpal#126]
Am I missing something? when I build the airpal, the following exception throwed: 

:buildAssets
module.js:338
    throw err;
          ^
Error: Cannot find module 'cl-strings'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ricdong/workspace/install/cdh/airpal-master/src/main/resources/assets/node_modules/browser-sync/lib/messages.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
:buildAssets FAILED

FAILURE: Build failed with an exception.

**Comment by tonywutao** [comment]
1. open src/main/resources/assets/package.json
2. change the browser-sync to latest 2.8.1
