### ISSUE TITLE
Scheme not set error

### ISSUE THREAD

**Issue by Charles-Go** [airbnb/airpal#128]
I get a weird error when I'm trying to run Airpal connecting to presto. I'm running presto-server 0.107.
Any idea how to solve this?

Command used:
`java -server      -Duser.timezone=UTC      -cp build/libs/airpal-*-all.jar com.airbnb.airpal.AirpalApplication server reference.yml`

```
WARN  [2015-08-08 01:41:55,233] com.google.common.cache.LocalCache: Exception thrown during refresh
! java.lang.IllegalStateException: scheme has not been set
! at com.google.common.base.Preconditions.checkState(Preconditions.java:173) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.airlift.http.client.HttpUriBuilder.build(HttpUriBuilder.java:234) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.facebook.presto.client.StatementClient.buildQueryRequest(StatementClient.java:87) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.facebook.presto.client.StatementClient.<init>(StatementClient.java:81) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.presto.QueryRunner.startInternalQuery(QueryRunner.java:30) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.core.execution.QueryClient.executeWith(QueryClient.java:39) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.presto.metadata.SchemaCache.queryMetadata(SchemaCache.java:78) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.presto.metadata.SchemaCache.access$000(SchemaCache.java:35) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.presto.metadata.SchemaCache$1.load(SchemaCache.java:58) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.presto.metadata.SchemaCache$1.load(SchemaCache.java:54) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2325) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! ... 7 common frames omitted
! Causing: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: scheme has not been set
! at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$Segment$1.run(LocalCache.java:2331) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:101) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:170) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2326) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2389) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache.refresh(LocalCache.java:4090) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$LocalLoadingCache.refresh(LocalCache.java:4843) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.presto.metadata.SchemaCache$3.run(SchemaCache.java:123) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

**Comment by qwwqwwq** [comment]
Got the same error while trying the AWS airpal example here:

https://blogs.aws.amazon.com/bigdata/post/Tx1BF2DN6KRFI27/Analyze-Data-with-Presto-and-Airpal-on-Amazon-EMR

The problem was when I provided the public DNS of the EMR master node, I provided it like:

`ec2-xxx.us-west-2.compute.amazonaws.com`

when it should be

http://`ec2-xxx.us-west-2.compute.amazonaws.com`

`scheme has not been set` refers to the URI `http` scheme missing from the presto URI
