### ISSUE TITLE
I am getting the following errors when trying to install airpal

### ISSUE THREAD

**Issue by rraghuram64** [airbnb/airpal#147]
Hello,

I am getting the following issues when installing the airpal.

Command:./gradlew clean shadowJar

> contextify@0.1.14 install /home/ec2-user/airpal/src/main/resources/assets/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.33"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/ec2-user/airpal/src/main/resources/assets/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/.node-gyp"
make: Entering directory `/home/ec2-user/airpal/src/main/resources/assets/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
make: g++: Command not found
make: Leaving directory `/home/ec2-user/airpal/src/main/resources/assets/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/build'
make: *** [Release/obj.target/contextify/src/contextify.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.gradle/nodejs/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 4.1.10-17.31.amzn1.x86_64
gyp ERR! command "node" "/root/.gradle/nodejs/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/airpal/src/main/resources/assets/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.10-17.31.amzn1.x86_64
npm ERR! command "/root/.gradle/nodejs/node-v0.10.33-linux-x64/bin/node" "/root/.gradle/nodejs/node-v0.10.33-linux-x64/lib/node_modules/npm/bin/npm-cli.js" "install"
npm ERR! cwd /home/ec2-user/airpal/src/main/resources/assets
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
:installAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installAssets'.
> Process 'command '/root/.gradle/nodejs/node-v0.10.33-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by kyleburke** [comment]
I was able to get around a similar error by not specifying the prestoVersion. Not sure if it will work but you may want to try it.

Try this:
sudo ./gradlew clean shadowJar

**Comment by rraghuram64** [comment]
Yup that works for me but when I go to the next step to specify the presto version its fails.

**Comment by kyleburke** [comment]
Are you saying the build did not work? After the build, the next two steps are create mysql database and setup reference.yml. After that you do the migrate database step. Which step is failing?

**Comment by rraghuram64** [comment]
I did the following
1-./gradlew clean shadowJar -Dairpal.useLocalNode   this was sucessfull

Do I need to run the following one ./gradlew -Dairpal.prestoVersion=0.85 (when running this is failing )clean shadowJar or go to the next step creating the SQL database.

**Comment by kyleburke** [comment]
If you have node and npm install locally that should be fine and you can go to next step.

**Comment by rraghuram64** [comment]
Cool.Then I will try and update you if I am successful.

**Comment by rraghuram64** [comment]
I followed the steps but when I open the browser I just get blank screen

![image](https://cloud.githubusercontent.com/assets/12616596/11133763/957d08b2-895d-11e5-94e3-de3e5ef6580c.png)

**Comment by kyleburke** [comment]
I'm going to guess that your issue is a misconfiguration in reference.yml. I got it working in my environment tonight and all my issues involved not setting up reference.yml and connectivity with my EMR cluster. My other suggestion is to make sure you can connect with presto-cli tool first. I also had some misconfigurations in my config files for presto.

**Comment by rraghuram64** [comment]
@kyleburke I tried number of times but I get a blank page when I open the UI.I would appreciate if you can share what you have done with the configurations.

Also when you say "make sure you can connect with presto-cli tool first " Do you mean to test it on the EMR cluster ,If that the case I am able to run connect and run some sample queries from presto cli on EMR.

**Comment by miry** [comment]
I had same issue if I specify `-Dairpal.prestoVersion=0.138`

**Comment by surendraGaddam99** [comment]
Getting blank screen after running Airpal .  Please suggest steps to resolve this .
![image](https://cloud.githubusercontent.com/assets/19906954/16005088/f86dd442-3182-11e6-97f8-e2ac69b24d63.png)


PFA  my reference.yml  file
![image](https://cloud.githubusercontent.com/assets/19906954/16005177/7ff47d94-3183-11e6-8e48-4bcbe5f26e13.png)

**Comment by miry** [comment]
@surendraGaddam99 try this branch: https://github.com/pubnative/airpal/tree/devel

**Comment by surendraGaddam99** [comment]
Hi ,

What things needs to be installed and configured as part of PrestoDB  for running Airpal application.

Thanks
Surendra

**Comment by 414135289** [comment]
@surendraGaddam99  I got the same issues. Did you solve this problem?

**Comment by akalakoti** [comment]
Hi,

I am also facing same error.. the BUILD SUCCESSFUL when i ran without presto versio. Not sure how it will work further.

**Comment by miry** [comment]
@akalakoti I suggest to use Metabase or Redash instead of airpal.
