### ISSUE TITLE
open airpal in browser will be error

### ISSUE THREAD

**Issue by Anne623** [airbnb/airpal#190]
Hi, all, I run airpal with ```java -server \
     -Duser.timezone=UTC \
     -cp build/libs/airpal-*-all.jar com.airbnb.airpal.AirpalApplication server reference.yml```
the log is ok. but when i open ```http://localhost:8081``` in browser, the log show error:
```
ERROR [2016-07-14 08:24:16,194] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 6e1240d1cf573c50
! java.nio.channels.UnresolvedAddressException: null
! at org.eclipse.jetty.util.SocketAddressResolver$1.run(SocketAddressResolver.java:155) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! ... 3 common frames omitted
! Causing: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.channels.UnresolvedAddressException
! at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.presto.metadata.SchemaCache.getSchemaMap(SchemaCache.java:136) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.airbnb.airpal.resources.TablesResource.getTableUpdates(TablesResource.java:74) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_11]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_11]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_11]
! at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_11]
! at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.dropwizard.jersey.guava.OptionalResourceMethodDispatchAdapter$OptionalRequestDispatcher.dispatch(OptionalResourceMethodDispatchAdapter.java:37) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:348) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:127) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:175) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:162) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.Server.handle(Server.java:446) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [airpal-0.1.0-SNAPSHOT-all.jar:na]
! at java.lang.Thread.run(Thread.java:722) [na:1.7.0_11]
```

but i can open the url. 
while there are no tables in app page, when i use ```SELECT * from test```, nothing happed. the log is :
```
INFO  [2016-07-14 08:30:57,102] com.airbnb.shiro.filter.AllowAllFilter: onAccessDenied called
INFO  [2016-07-14 08:30:57,102] com.airbnb.shiro.filter.AllowAllFilter: createToken called
WARN  [2016-07-14 08:30:57,103] com.airbnb.shiro.SessionListenerLogger: Saw START of Session: [org.apache.shiro.session.mgt.SimpleSession,id=bf79fc9b-a436-4b8d-8702-b1af7ea8bc45]
19.921.120.254 -  -  [14/Jul/2016:08:30:57 +0000] "PUT /api/execute HTTP/1.1" 200 - "http://19.921.120.254:8081/app" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" 5
```

does some configuration error?

**Comment by surendraGaddam99** [comment]
That error is because you didnt provide valid presto co-ordinator url in reference.yml file. You need to configure presto server and provide the url in refernce.yml file.Then you can execute the queries in Airpal editor.

Thanks
Surendra

**Comment by Anne623** [comment]
@surendraGaddam99 , yes, thank you. I configure presto and it work fine.
