### ISSUE TITLE
Build error by default build command with presto version 0.221

### ISSUE THREAD

**Issue by wupan-olo** [airbnb/airpal#234]
OS centos7
Java version "1.8.0_112"
Use default build command: `./gradlew -Dairpal.prestoVersion=0.221 clean shadowJar`
Fail mesage:

```
npm WARN unmet dependency which is version 6.0.2
:buildAssets

module.js:340
    throw err;
          ^
Error: Cannot find module 'copy-descriptor'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/data/panwu2/software/airpal/src/main/resources/assets/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/micromatch/node_modules/snapdragon/node_modules/base/node_modules/class-utils/node_modules/static-extend/node_modules/object-copy/index.js:4:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
:buildAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildAssets'.
> Process 'command '/root/.gradle/nodejs/node-v0.10.33-linux-x64/bin/node'' finished with non-zero exit value 8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by wupan-olo** [comment]
Same error throw on build command: `./gradlew  clean shadowJar`

**Comment by DHARESHWAR** [comment]
I am facing the same issue. Any workaround to this issue ?

**Comment by tigerneil** [comment]
me too
